zookeeper:
  #每次重试时间间隔，单位毫秒
  baseSleepTimeMs: 1000
  #重试次数
  maxRetries: 3
  #zookeeper服务连接id与端口
  connectString: 127.0.0.1:2181
  #会话超时时间，单位毫秒
  sessionTimeoutMs: 5000
  #连接创建超时时间，单位毫秒
  connection-timeout-ms: 5000

#Redission 哨兵配置
#sentinelServersConfig:
#  idleConnectionTimeout: 10000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  slaveSubscriptionConnectionMinimumIdleSize: 1
#  slaveSubscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 32
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 32
#  masterConnectionPoolSize: 64
#  readMode: SLAVE
#  sentinelAddresses:
#    - redis://192.168.157.130:26379
#    - redis://192.168.157.130:26380
#    - redis://192.168.157.130:26381
#  masterName: mymaster
#  database: 0
#threads: 0
#nettyThreads: 0

#redis单机配置
#singleServerConfig:
#  idleConnectionTimeout: 10000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  address: "redis://192.168.157.130:6379"
#  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 50
#  connectionMinimumIdleSize: 32
#  connectionPoolSize: 64
#  database: 0
#  dnsMonitoringInterval: 5000
#threads: 0
#nettyThreads: 0


#redis 集群
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  slaveSubscriptionConnectionMinimumIdleSize: 1
  slaveSubscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
    - "redis://127.0.0.1:7004"
    - "redis://127.0.0.1:7001"
    - "redis://127.0.0.1:7000"
  scanInterval: 1000
threads: 0
nettyThreads: 0
